#line 2 "lex.yy.cpp"
/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>


/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 76
#define YY_END_OF_BUFFER 77
static yyconst short int yy_accept[181] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    2,
        6,    6,   77,   75,   74,   72,   61,   23,    1,   75,
       75,   36,   48,   49,   52,   50,   45,   51,   44,   53,
       65,   65,   43,   56,   54,   57,   75,   66,   46,   47,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       75,   41,   24,   76,   35,   76,   76,   37,   40,   76,
        2,    6,    5,    6,   74,   73,   72,   58,   67,   60,
       64,   65,    0,    0,    0,   55,    0,    0,   68,   71,
       66,   70,   66,   66,   19,   66,   66,   66,   13,   66,
       66,   66,   66,   66,   66,   59,   42,   24,   34,   27,

       28,   32,   33,   26,   25,   29,   30,   31,   37,   39,
       38,    2,    6,    6,   73,   67,   64,    0,   62,   63,
        0,   69,   68,   66,    9,   66,   12,   66,   66,   66,
       66,   66,   66,   66,   66,    6,   62,    0,   63,    0,
        0,   69,   66,    0,    0,   14,   66,   66,   66,   66,
       16,   22,   66,   66,   66,    4,    0,    7,    0,    0,
        0,   15,   21,   66,    8,   66,   18,   17,    3,    0,
       11,   20,    0,    0,    0,    0,   10,    0,    0,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    1,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,    1,   22,   23,
       24,   25,   26,   27,   28,   28,   28,   28,   28,   28,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       30,   31,   32,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   29,   29,   43,   29,   44,
       45,   46,   29,   47,   48,   49,   50,   29,   51,   52,
       29,   29,   53,   54,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    1,    2,    3,    4,    4,    1,    1,    5,    1,
        1,    1,    1,    1,    1,    1,    1,    6,    6,    6,
        6,    1,    1,    1,    1,    3,    7,    8,    9,    1,
       10,    1,   11,    8,    8,    8,    8,    8,    8,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    4,    1,    4
    } ;

static yyconst short int yy_base[198] =
    {   0,
        0,    0,   53,   57,   58,   61,    0,    0,  313,  269,
       54,   62,  268,  523,  264,   66,  241,  523,  523,    0,
      214,  523,  523,  523,  523,  523,  523,  523,  523,  523,
       61,   54,  523,  523,   42,  523,  194,   67,  523,  523,
       72,   79,   93,   95,   81,   96,   97,   99,  100,  107,
      165,  208,    0,  523,  523,  154,  144,    0,  523,   86,
        0,    0,  523,  166,  201,   88,  125,  523,    0,  523,
      136,  140,  161,  113,    0,  523,  149,    0,    0,  523,
      112,  523,  163,  146,  148,  164,  172,  173,  174,  179,
      180,  182,  191,  197,  192,  523,  523,    0,  523,  523,

      523,  211,  523,  523,  523,  523,  523,  523,    0,  523,
      523,    0,    0,  127,  139,    0,  217,  224,  192,  137,
      111,    0,    0,  223,  249,  235,  198,  243,  229,  244,
      250,  252,  254,  255,  258,  108,  267,  269,  110,  106,
       93,    0,  263,  212,  261,  270,  279,  289,  291,  294,
      295,  299,  300,  302,  304,    0,   74,  303,   76,  310,
      320,  306,  310,  320,  327,  329,  330,  331,  523,   66,
      333,  335,   63,  347,  349,  364,  523,  367,  369,  523,
      385,  396,  407,  418,  422,  427,  436,  447,  458,  469,
      480,  486,  492,  493,  499,  505,  511

    } ;

static yyconst short int yy_def[198] =
    {   0,
      180,    1,  181,  181,  182,  182,    1,    1,  183,  183,
      184,  184,  180,  180,  180,  180,  180,  180,  180,  185,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  186,  187,  180,  180,
      187,  187,  187,  187,  187,  187,  187,  187,  187,  187,
      180,  180,  188,  180,  180,  180,  180,  189,  180,  180,
      190,  191,  180,  191,  180,  180,  180,  180,  192,  180,
      180,  180,  180,  180,  193,  180,  180,  194,  195,  180,
      187,  180,  187,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  180,  180,  188,  180,  180,

      180,  180,  180,  180,  180,  180,  180,  180,  189,  180,
      180,  190,  191,  191,  180,  192,  180,  180,  180,  196,
      180,  197,  195,  187,  187,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  191,  180,  180,  196,  196,
      180,  197,  187,  180,  180,  187,  187,  187,  187,  187,
      187,  187,  187,  187,  187,  191,  180,  187,  180,  180,
      180,  187,  187,  187,  187,  187,  187,  187,  180,  180,
      187,  187,  180,  180,  180,  180,  180,  180,  180,    0,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180

    } ;

static yyconst short int yy_nxt[579] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   32,
       32,   33,   34,   35,   36,   14,   37,   38,   38,   39,
       14,   40,   38,   38,   38,   41,   42,   43,   44,   38,
       38,   45,   38,   38,   38,   38,   46,   47,   48,   49,
       50,   38,   14,   51,   52,   54,   63,   55,   56,   54,
       54,   55,   56,   54,   63,   76,   59,   66,   67,   59,
       80,   72,   72,   72,   72,   80,   77,   64,   71,   71,
       71,   72,   80,   57,   80,   64,   73,   57,   60,   66,
      115,   60,   82,   73,  110,   74,   80,   82,   80,   80,

       80,  174,   80,   80,   82,   54,   82,   54,  173,   54,
       80,   54,   75,  170,   83,   80,   84,  169,   82,   89,
       82,   82,   82,   85,   82,   82,   66,   67,   88,  111,
      119,  119,   82,   90,  157,   86,   87,   82,  140,   92,
       66,  115,  140,   94,  156,   93,   91,   95,  100,   80,
      141,   80,  101,  117,  117,  117,   72,   72,   72,   72,
       72,  102,  102,  102,  102,  103,   80,   80,  118,  140,
      136,   82,   73,   82,  104,   80,   80,   80,   72,   72,
       72,   72,   80,   80,  125,   80,  121,  105,   82,   82,
      106,  107,  108,   73,   80,   80,  124,   82,   82,   82,

       80,   80,   65,  114,   82,   82,   99,   82,  127,  137,
      137,  126,   97,  144,  145,  128,   82,   82,   96,  131,
       78,   70,   82,   82,  138,  130,   80,  129,  102,  102,
      102,  102,   80,  135,  117,  117,  117,   72,   80,  133,
      132,  117,  117,  117,   72,  134,   80,   80,   82,  118,
      144,  145,   80,   80,   82,   80,  118,   80,   80,  159,
       82,   80,  160,  161,   68,   65,   80,  180,   82,   82,
      143,   54,  146,   80,   82,   82,  147,   82,  149,   82,
       82,  150,   80,   82,  137,  137,  137,  137,   82,  152,
      148,  153,   80,  151,   80,   82,  154,   80,   80,  138,

      155,  138,   80,   80,   82,   80,   80,   80,  159,   80,
      158,  160,  161,   80,   82,   54,   82,  162,  180,   82,
       82,  160,  161,   80,   82,   82,  163,   82,   82,   82,
       80,   82,   80,   80,   80,   82,   80,  164,   80,  180,
      165,  168,  180,  180,  167,   82,  180,  166,  175,  176,
      175,  176,   82,  180,   82,   82,   82,  159,   82,  180,
       82,  180,  177,  171,  177,  178,  179,  159,  178,  179,
      178,  179,  180,  180,  180,  180,  172,  180,  180,  177,
      180,  180,  177,  180,  177,   53,   53,   53,   53,   53,
       53,   53,   53,   53,   53,   53,   58,   58,   58,   58,

       58,   58,   58,   58,   58,   58,   58,   61,   61,   61,
       61,   61,   61,   61,   61,   61,   61,   61,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   69,
       69,  180,   69,   79,   79,   79,  180,   79,   81,  180,
      180,   81,  180,   81,   81,  180,   81,   98,  180,   98,
      180,   98,   98,   98,   98,   98,  180,   98,  109,  180,
      109,  109,  180,  109,  109,  109,  109,  180,  109,  112,
      180,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      113,  180,  113,  113,  113,  113,  113,  113,  113,  113,
      113,  116,  180,  116,  116,  180,  116,  120,  180,  120,

      122,  122,  180,  122,  123,  180,  123,  123,  180,  123,
      139,  180,  139,  180,  180,  139,  142,  180,  142,  142,
      180,  142,   13,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180
    } ;

static yyconst short int yy_chk[579] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,   11,    3,    3,    4,
        5,    4,    4,    6,   12,   35,    5,   16,   16,    6,
       38,   32,   32,   32,   32,   41,   35,   11,   31,   31,
       31,   31,   42,    3,   45,   12,   32,    4,    5,   66,
       66,    6,   38,   31,   60,   31,   43,   41,   44,   46,

       47,  173,   48,   49,   42,    3,   45,    3,  170,    4,
       50,    4,   31,  159,   41,   81,   42,  157,   43,   45,
       44,   46,   47,   42,   48,   49,   67,   67,   44,   60,
       74,   74,   50,   46,  141,   43,   43,   81,  140,   48,
      115,  115,  139,   49,  136,   48,   47,   50,   57,   84,
      121,   85,   57,   71,   71,   71,   71,   72,   72,   72,
       72,   57,   57,   57,   57,   57,   83,   86,   71,  120,
      114,   84,   72,   85,   57,   87,   88,   89,   73,   73,
       73,   73,   90,   91,   84,   92,   77,   57,   83,   86,
       57,   57,   57,   73,   93,   95,   83,   87,   88,   89,

       94,  127,   65,   64,   90,   91,   56,   92,   87,  119,
      119,   86,   52,  144,  144,   88,   93,   95,   51,   92,
       37,   21,   94,  127,  119,   91,  124,   90,  102,  102,
      102,  102,  129,   95,  117,  117,  117,  117,  126,   94,
       93,  118,  118,  118,  118,   94,  128,  130,  124,  117,
      125,  125,  125,  131,  129,  132,  118,  133,  134,  144,
      126,  135,  145,  145,   17,   15,  143,   13,  128,  130,
      124,   10,  126,  146,  125,  131,  126,  132,  129,  133,
      134,  130,  147,  135,  137,  137,  138,  138,  143,  132,
      128,  133,  148,  131,  149,  146,  134,  150,  151,  137,

      135,  138,  152,  153,  147,  154,  158,  155,  145,  162,
      143,  160,  160,  163,  148,    9,  149,  147,    0,  150,
      151,  161,  161,  164,  152,  153,  148,  154,  158,  155,
      165,  162,  166,  167,  168,  163,  171,  149,  172,    0,
      150,  155,    0,    0,  154,  164,    0,  153,  174,  174,
      175,  175,  165,    0,  166,  167,  168,  160,  171,    0,
      172,    0,  174,  164,  175,  176,  176,  161,  178,  178,
      179,  179,    0,    0,    0,    0,  166,    0,    0,  176,
        0,    0,  178,    0,  179,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  181,  181,  182,  182,  182,  182,

      182,  182,  182,  182,  182,  182,  182,  183,  183,  183,
      183,  183,  183,  183,  183,  183,  183,  183,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  185,
      185,    0,  185,  186,  186,  186,    0,  186,  187,    0,
        0,  187,    0,  187,  187,    0,  187,  188,    0,  188,
        0,  188,  188,  188,  188,  188,    0,  188,  189,    0,
      189,  189,    0,  189,  189,  189,  189,    0,  189,  190,
        0,  190,  190,  190,  190,  190,  190,  190,  190,  190,
      191,    0,  191,  191,  191,  191,  191,  191,  191,  191,
      191,  192,    0,  192,  192,    0,  192,  193,    0,  193,

      194,  194,    0,  194,  195,    0,  195,  195,    0,  195,
      196,    0,  196,    0,    0,  196,  197,    0,  197,  197,
        0,  197,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,
      180,  180,  180,  180,  180,  180,  180,  180
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lexer.flex"
#define INITIAL 0
#line 2 "lexer.flex"
	#include <stdio.h> 
	#include <locale.h>
	#include <string.h>
    #include "parser_tab.h"
	#include "structures.h"
	#include "test.h"
#define YY_NEVER_INTERACTIVE 1
#define STRING_X 1

#define STRING2 2

#define EXP_IN_STRING 3

#define LINE_COMMENT 4

#define MULTILINE_COMMENT 5

#line 572 "lex.yy.cpp"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 23 "lexer.flex"


 
	char comment[1000];
	char literal[1000];
	char temp[1000];
 

#line 728 "lex.yy.cpp"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 181 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 523 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 31 "lexer.flex"
{
	comment[0] = 0; 
	BEGIN(LINE_COMMENT);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "lexer.flex"
{
	strcat(comment, yytext); 
	//printf("%s\t\tline comment\n",comment);
	BEGIN(INITIAL);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "lexer.flex"
{
	BEGIN(MULTILINE_COMMENT);
	comment[0] = 0;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "lexer.flex"
{
	BEGIN(INITIAL);
	//printf("%s\t\tmultiline comment\n", comment);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 49 "lexer.flex"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 50 "lexer.flex"
strcat(comment, yytext);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "lexer.flex"
return CLASS;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "lexer.flex"
return SUPER;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "lexer.flex"
return DEF;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "lexer.flex"
return DEF_STATIC;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "lexer.flex"
return RETURN;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "lexer.flex"
return END;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 60 "lexer.flex"
return IF;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 61 "lexer.flex"
return ELSE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 62 "lexer.flex"
return ELSIF;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 63 "lexer.flex"
return THEN;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 64 "lexer.flex"
return WHILE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "lexer.flex"
return UNTIL;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 66 "lexer.flex"
return DO;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 67 "lexer.flex"
return UNLESS;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 69 "lexer.flex"
return FALSE;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 70 "lexer.flex"
return TRUE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 72 "lexer.flex"
{ literal[0] = 0;
    BEGIN(STRING_X);
    }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 75 "lexer.flex"
strcat(literal,yytext);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 76 "lexer.flex"
strcat(literal,"\n");
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 77 "lexer.flex"
strcat(literal,"\\");
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 78 "lexer.flex"
strcat(literal,"\"");
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 79 "lexer.flex"
strcat(literal,"\'");
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 80 "lexer.flex"
strcat(literal,"\r");
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "lexer.flex"
strcat(literal," ");
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 82 "lexer.flex"
strcat(literal,"\t");
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "lexer.flex"
{
	int result;
	sscanf(yytext+1,"%o",&result);
	sprintf(literal + strlen(literal),"%c",result);
    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 88 "lexer.flex"

	YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "lexer.flex"
{
    BEGIN(INITIAL);
	
	char * ttt = (char*)malloc(sizeof(char)*strlen(literal)+3);
	ttt[0]= 0;
	strcat(ttt,"\"");
	strcat(ttt,literal);
	strcat(ttt,"\"+(");
	strcpy(literal,ttt);
	

	char *p = ttt;
	char *q = p + strlen(p);
	while(q > p)
		unput(*--q);
	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 105 "lexer.flex"
{ 
	BEGIN(INITIAL);
	yylval.uString = (char*)malloc(sizeof(char)*strlen(literal)+1);
	strcpy(yylval.uString,literal);
	return STRING;
    }	
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 111 "lexer.flex"
{ literal[0] = 0;
    BEGIN(STRING2);
    }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 114 "lexer.flex"
strcat(literal,yytext);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 115 "lexer.flex"
strcat(literal,"\n");
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 116 "lexer.flex"
strcat(literal,"\'");
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 117 "lexer.flex"
{
	BEGIN(INITIAL);
	yylval.uString = (char*)malloc(sizeof(char)*strlen(literal)+1);
	strcpy(yylval.uString,literal);
	return STRING;
    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 123 "lexer.flex"
{
	//BEGIN(STRING_X);
	literal[0] = 0;
	strcat(literal,")+\"");
	char *p = literal;
	char *q = p + strlen(p);
	while(q > p)
		unput(*--q);
	literal[0] = 0;
	
    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 134 "lexer.flex"
{
		unput(')');
	}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 138 "lexer.flex"
return ';';
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 139 "lexer.flex"
return '.';
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 140 "lexer.flex"
return ',';
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 141 "lexer.flex"
return '[';
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 142 "lexer.flex"
return ']';
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 143 "lexer.flex"
return '(';
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 144 "lexer.flex"
return ')';
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 145 "lexer.flex"
return '+';
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 146 "lexer.flex"
return '-';
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 147 "lexer.flex"
return '*';
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 148 "lexer.flex"
return '/';
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 149 "lexer.flex"
return '=';
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 150 "lexer.flex"
return EQUAL;
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 151 "lexer.flex"
return '<';
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 152 "lexer.flex"
return '>';
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 153 "lexer.flex"
return NOTEQUAL;
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 154 "lexer.flex"
return OR;
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 155 "lexer.flex"
return AND;
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 156 "lexer.flex"
return '!';
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 158 "lexer.flex"
{
    int i, len = 0;
	long result;
	char *stop;
    for(i = 2; i < strlen(yytext); i++)
	    if(yytext[i] != '_')
            temp[len++] = yytext[i];
    temp[len] = '\0';
	result = strtol(temp, &stop, 2);
    //printf("%s => %ld\t\tbin constant\n", temp, result);
	yylval.uInt = result;
	return INT;
    }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 171 "lexer.flex"
{
    int i, len = 0;
	int result;
    for(i = 0; i < strlen(yytext); i++)
	    if(yytext[i] != '_')
            temp[len++] = yytext[i];
    temp[len] = '\0';
	_strupr(temp);
	sscanf(temp, "%X", &result);
   // printf("%s => %d\t\thex constant\n", temp, result);
    yylval.uInt = result;
	return INT;
    }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 184 "lexer.flex"
{
    int i, len = 0;
	int result;
    for(i = 0; i < strlen(yytext); i++)
	    if(yytext[i] != '_')
            temp[len++] = yytext[i];
    temp[len] = '\0';
	sscanf(temp, "%o", &result);
    //printf("%s => %d\t\toct constant\n", temp, result);
	yylval.uInt = result;
	return INT;
    }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 196 "lexer.flex"
{
    int i, len = 0;
	int result;
    for(i = 0; i < strlen(yytext); i++)
	    if(yytext[i] != '_')
            temp[len++] = yytext[i];
    temp[len] = '\0';
	sscanf(temp, "%d", &result);
    //printf("%s => %d\t\tdec constant\n", temp, result);
	yylval.uInt = result;
	return INT;
    }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 208 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return ID;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 213 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return ID;
}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 218 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return IDFIELD;
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 223 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return ID_STATIC_FIELD;
}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 228 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return ID;
}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 233 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return ID;
}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 239 "lexer.flex"
return EOL;
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 240 "lexer.flex"
return EOL;
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 242 "lexer.flex"

	YY_BREAK
case 75:
YY_RULE_SETUP
#line 244 "lexer.flex"
printf("Error, unexpected lexem %s !!!!!!\n", yytext);
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 246 "lexer.flex"
ECHO;
	YY_BREAK
#line 1319 "lex.yy.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING_X):
case YY_STATE_EOF(STRING2):
case YY_STATE_EOF(EXP_IN_STRING):
case YY_STATE_EOF(LINE_COMMENT):
case YY_STATE_EOF(MULTILINE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 181 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 181 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 180);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 246 "lexer.flex"




