/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.85 95/04/24 10:48:47 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)


#define yywrap() 1
#define YY_SKIP_YYWRAP
typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 82
#define YY_END_OF_BUFFER 83
static yyconst short int yy_accept[179] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    2,    2,
        6,    6,   83,   81,   79,   80,   67,   24,    1,   81,
       81,   42,   54,   55,   58,   56,   49,   57,   48,   59,
       71,   71,   47,   62,   60,   63,   81,   72,   52,   53,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   50,   81,   51,   25,   82,   41,   35,   82,   43,
       46,   82,   81,   38,   39,    2,    6,    5,    6,   79,
       80,   64,   73,   66,   70,   71,    0,    0,    0,   61,
        0,    0,   74,   77,   72,   78,   76,   72,   72,   19,
       72,   72,   72,   13,   72,   72,   72,   72,   72,   72,

       72,   72,   65,   25,   28,   29,   33,   34,   27,   26,
       30,   31,   32,   43,   45,   44,   36,   40,    2,    6,
        6,   73,   70,    0,   68,   69,    0,   75,   74,   72,
       10,   72,   12,   72,   23,   72,   72,   72,   72,   72,
       72,   72,   72,   37,   36,    6,   68,    0,   69,    0,
        0,   75,   72,   14,   72,   72,   72,    9,   72,   16,
       22,   72,   72,   72,    4,    0,    7,   15,   21,   72,
        8,   72,   18,   17,    3,   11,   20,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    7,    1,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   20,
       20,   20,   20,   20,   20,   21,   21,    1,   22,   23,
       24,   25,   26,   27,   28,   28,   28,   28,   28,   28,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       29,   29,   29,   29,   29,   29,   29,   29,   29,   29,
       30,   31,   32,    1,   33,    1,   34,   35,   36,   37,

       38,   39,   40,   41,   42,   29,   29,   43,   29,   44,
       45,   46,   29,   47,   48,   49,   50,   29,   51,   52,
       29,   29,   53,   54,   55,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[56] =
    {   0,
        1,    1,    2,    3,    4,    5,    1,    1,    6,    1,
        1,    1,    1,    1,    1,    1,    1,    7,    7,    7,
        7,    1,    1,    3,    1,    3,    8,    9,   10,    1,
       11,    1,   12,    9,    9,    9,    9,    9,    9,   10,
       10,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,    5,    1,    5
    } ;

static yyconst short int yy_base[198] =
    {   0,
        0,    0,   53,   57,   58,   61,   50,   58,  209,  206,
       63,   66,  204,  638,  199,  181,  156,  638,  638,    0,
      170,  638,  638,  638,  638,  638,  638,  638,  638,  638,
       62,   53,  638,  638,   44,  638,  150,   72,  638,  638,
       95,   96,  100,  103,  121,  124,  127,  131,  132,  128,
      135,  638,  121,  638,    0,  638,  638,  638,  177,    0,
      638,  124,    0,  638,  169,    0,    0,  638,  129,  161,
      146,  638,    0,  638,   97,  169,  173,   59,    0,  638,
      108,    0,    0,  638,  138,  638,  638,  179,  196,  203,
      206,  207,  210,  213,  214,  219,  224,  237,  238,  245,

      248,  251,  638,    0,  638,  638,  260,  638,  638,  638,
      638,  638,  638,    0,  638,  638,  135,  638,    0,    0,
       79,    0,  266,  282,  152,   76,   62,    0,    0,  266,
      284,  285,  292,  300,  308,  309,  313,  316,  317,  325,
      332,  340,  341,  638,   96,   57,  240,  350,   60,   58,
       43,    0,  349,  353,  367,  370,  374,  377,  381,  385,
      386,  391,  398,  409,    0,   31,  410,  414,  419,  422,
      425,  426,  433,  438,  638,  449,  452,  638,  478,  490,
      502,  514,  518,  523,  533,  545,  557,  561,  573,  585,
      591,  597,  598,  604,  613,  619,  625

    } ;

static yyconst short int yy_def[198] =
    {   0,
      178,    1,  179,  179,  180,  180,    1,    1,  181,  181,
      182,  182,  178,  178,  178,  178,  178,  178,  178,  183,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  184,  185,  178,  178,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  178,  178,  178,  186,  178,  178,  178,  178,  187,
      178,  178,  188,  178,  178,  189,  190,  178,  190,  178,
      178,  178,  191,  178,  178,  178,  178,  178,  192,  178,
      178,  193,  194,  178,  185,  178,  178,  185,  185,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,

      185,  185,  178,  186,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  187,  178,  178,  195,  178,  189,  190,
      190,  191,  178,  178,  178,  196,  178,  197,  194,  185,
      185,  185,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  178,  195,  190,  178,  178,  196,  196,
      178,  197,  185,  185,  185,  185,  185,  185,  185,  185,
      185,  185,  185,  185,  190,  178,  185,  185,  185,  185,
      185,  185,  185,  185,  178,  185,  185,    0,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178

    } ;

static yyconst short int yy_nxt[694] =
    {   0,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   28,   29,   30,   31,   32,   32,
       32,   33,   34,   35,   36,   14,   37,   38,   38,   39,
       14,   40,   38,   38,   38,   41,   42,   43,   44,   38,
       38,   45,   38,   46,   38,   38,   47,   48,   49,   50,
       51,   38,   52,   53,   54,   56,   63,   57,   58,   56,
       56,   57,   58,   56,   63,   68,   61,   80,   68,   61,
       76,   76,   76,   76,  175,   84,  125,  125,   81,   75,
       75,   75,   76,   59,  166,   77,   69,   59,   62,   69,
      150,   62,  150,  165,   77,   86,   78,   87,   84,   84,

      144,  151,   64,   84,   65,   56,   84,   56,  150,   56,
       64,   56,   65,   79,  123,  123,  123,   76,   86,   86,
       87,   87,  146,   86,   84,   87,   86,   84,   87,  124,
       84,   84,  115,   89,   84,   84,   93,   88,   84,  144,
       90,   84,   91,   92,   86,  127,   87,   86,   71,   87,
       86,   86,   87,   87,   86,   86,   87,   87,   86,   94,
       87,   86,   70,   87,   96,   95,  121,  116,   97,  147,
      147,  101,   99,  118,  103,  102,   82,   74,  100,   72,
       98,  105,   84,   71,  148,  106,   76,   76,   76,   76,
       76,   76,   76,   76,  107,  107,  107,  107,  108,   84,

       70,   77,   86,  178,   87,   77,   84,  109,   56,   84,
       84,   56,  130,   84,  178,  178,   84,   84,  178,   86,
      110,   87,   84,  111,  112,  113,   86,   84,   87,   86,
       86,   87,   87,   86,  131,   87,   86,   86,   87,   87,
       84,   84,   86,  133,   87,  178,  178,   86,   84,   87,
      178,   84,  134,  132,   84,  178,  135,  147,  147,  178,
       86,   86,   87,   87,  178,  178,  137,  136,   86,   84,
       87,   86,  148,   87,   86,  139,   87,  107,  107,  107,
      107,  178,  138,  123,  123,  123,   76,   84,   84,   86,
      141,   87,  143,  178,  140,   84,  142,  178,  124,  123,

      123,  123,   76,   84,  178,  178,  178,   86,   86,   87,
       87,   84,   84,  153,  124,   86,   84,   87,  178,   84,
       84,  178,  154,   86,  178,   87,  155,  178,   84,  178,
      178,   86,   86,   87,   87,   84,   86,  178,   87,   86,
       86,   87,   87,   84,   84,  178,  178,  156,   86,  178,
       87,  158,   84,  159,  178,   86,   84,   87,  157,  178,
      160,  178,  161,   86,   86,   87,   87,  147,  147,  162,
       84,  178,   86,   84,   87,  178,   86,   84,   87,  178,
       84,  163,  148,  164,   84,  178,  178,  178,   84,   84,
       86,  178,   87,   86,   84,   87,  167,   86,  178,   87,

       86,   84,   87,  178,   86,  168,   87,  169,   86,   86,
       87,   87,   84,   84,   86,  178,   87,   84,  178,  178,
      170,   86,   84,   87,  178,   84,  178,  171,   84,   84,
      178,  178,   86,   86,   87,   87,   84,   86,  172,   87,
      173,   84,   86,  178,   87,   86,  174,   87,   86,   86,
       87,   87,   84,  178,  178,   84,   86,  178,   87,  178,
      178,   86,  178,   87,  178,  176,  178,  178,  178,  178,
      178,  178,   86,  177,   87,   86,  178,   87,   55,   55,
       55,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,

       60,   60,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   73,   73,  178,   73,
       83,   83,   83,  178,   83,   85,  178,  178,  178,   85,
      178,   85,   85,  178,   85,  104,  178,  104,  178,  178,
      104,  104,  104,  104,  104,  178,  104,  114,  178,  114,
      114,  114,  178,  114,  114,  114,  114,  178,  114,  117,
      117,  178,  117,  119,  178,  119,  119,  119,  119,  119,
      119,  119,  119,  119,  119,  120,  178,  120,  120,  120,
      120,  120,  120,  120,  120,  120,  120,  122,  178,  122,

      122,  178,  122,  126,  178,  126,  128,  128,  178,  128,
      129,  178,  129,  129,  178,  129,  145,  178,  178,  145,
      178,  145,  145,  178,  145,  149,  178,  149,  178,  178,
      149,  152,  178,  152,  152,  178,  152,   13,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178

    } ;

static yyconst short int yy_chk[694] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    3,    7,    3,    3,    4,
        5,    4,    4,    6,    8,   11,    5,   35,   12,    6,
       32,   32,   32,   32,  166,   38,   78,   78,   35,   31,
       31,   31,   31,    3,  151,   32,   11,    4,    5,   12,
      150,    6,  149,  146,   31,   38,   31,   38,   41,   42,

      145,  127,    7,   43,    7,    3,   44,    3,  126,    4,
        8,    4,    8,   31,   75,   75,   75,   75,   41,   42,
       41,   42,  121,   43,   45,   43,   44,   46,   44,   75,
       47,   50,   62,   42,   48,   49,   44,   41,   51,  117,
       42,   85,   43,   43,   45,   81,   45,   46,   71,   46,
       47,   50,   47,   50,   48,   49,   48,   49,   51,   45,
       51,   85,   70,   85,   47,   46,   69,   62,   48,  125,
      125,   50,   49,   65,   53,   51,   37,   21,   49,   17,
       48,   59,   88,   16,  125,   59,   76,   76,   76,   76,
       77,   77,   77,   77,   59,   59,   59,   59,   59,   89,

       15,   76,   88,   13,   88,   77,   90,   59,   10,   91,
       92,    9,   88,   93,    0,    0,   94,   95,    0,   89,
       59,   89,   96,   59,   59,   59,   90,   97,   90,   91,
       92,   91,   92,   93,   89,   93,   94,   95,   94,   95,
       98,   99,   96,   92,   96,    0,    0,   97,  100,   97,
        0,  101,   93,   91,  102,    0,   95,  147,  147,    0,
       98,   99,   98,   99,    0,    0,   97,   96,  100,  130,
      100,  101,  147,  101,  102,   99,  102,  107,  107,  107,
      107,    0,   98,  123,  123,  123,  123,  131,  132,  130,
      101,  130,  102,    0,  100,  133,  101,    0,  123,  124,

      124,  124,  124,  134,    0,    0,    0,  131,  132,  131,
      132,  135,  136,  130,  124,  133,  137,  133,    0,  138,
      139,    0,  132,  134,    0,  134,  132,    0,  140,    0,
        0,  135,  136,  135,  136,  141,  137,    0,  137,  138,
      139,  138,  139,  142,  143,    0,    0,  134,  140,    0,
      140,  137,  153,  138,    0,  141,  154,  141,  136,    0,
      139,    0,  140,  142,  143,  142,  143,  148,  148,  141,
      155,    0,  153,  156,  153,    0,  154,  157,  154,    0,
      158,  142,  148,  143,  159,    0,    0,    0,  160,  161,
      155,    0,  155,  156,  162,  156,  153,  157,    0,  157,

      158,  163,  158,    0,  159,  155,  159,  156,  160,  161,
      160,  161,  164,  167,  162,    0,  162,  168,    0,    0,
      157,  163,  169,  163,    0,  170,    0,  159,  171,  172,
        0,    0,  164,  167,  164,  167,  173,  168,  162,  168,
      163,  174,  169,    0,  169,  170,  164,  170,  171,  172,
      171,  172,  176,    0,    0,  177,  173,    0,  173,    0,
        0,  174,    0,  174,    0,  170,    0,    0,    0,    0,
        0,    0,  176,  172,  176,  177,    0,  177,  179,  179,
      179,  179,  179,  179,  179,  179,  179,  179,  179,  179,
      180,  180,  180,  180,  180,  180,  180,  180,  180,  180,

      180,  180,  181,  181,  181,  181,  181,  181,  181,  181,
      181,  181,  181,  181,  182,  182,  182,  182,  182,  182,
      182,  182,  182,  182,  182,  182,  183,  183,    0,  183,
      184,  184,  184,    0,  184,  185,    0,    0,    0,  185,
        0,  185,  185,    0,  185,  186,    0,  186,    0,    0,
      186,  186,  186,  186,  186,    0,  186,  187,    0,  187,
      187,  187,    0,  187,  187,  187,  187,    0,  187,  188,
      188,    0,  188,  189,    0,  189,  189,  189,  189,  189,
      189,  189,  189,  189,  189,  190,    0,  190,  190,  190,
      190,  190,  190,  190,  190,  190,  190,  191,    0,  191,

      191,    0,  191,  192,    0,  192,  193,  193,    0,  193,
      194,    0,  194,  194,    0,  194,  195,    0,    0,  195,
        0,  195,  195,    0,  195,  196,    0,  196,    0,    0,
      196,  197,    0,  197,  197,    0,  197,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178,  178,  178,  178,  178,  178,  178,  178,
      178,  178,  178

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
char *yytext;
#line 1 "lexer.flex"
#define INITIAL 0
#line 2 "lexer.flex"
	#include <stdio.h> 
	#include <locale.h>
	#include <string.h>
	#include "parcer_tab.h"
	#include "structures.h"
	#include "test.h"
	
	struct ProgramNode* root;
#define YY_NEVER_INTERACTIVE 1
#define STRING 1

#define STRING2 2

#define EXP_IN_STRING 3

#define LINE_COMMENT 4

#define MULTILINE_COMMENT 5

#line 601 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 23 "lexer.flex"


 
	char comment[1000];
	char literal[1000];
	char temp[1000];
 

#line 757 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 179 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 638 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 31 "lexer.flex"
{
	comment[0] = 0; 
	BEGIN(LINE_COMMENT);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 35 "lexer.flex"
{
	strcat(comment, yytext); 
	//printf("%s\t\tline comment\n",comment);
	BEGIN(INITIAL);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 41 "lexer.flex"
{
	BEGIN(MULTILINE_COMMENT);
	comment[0] = 0;
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 45 "lexer.flex"
{
	BEGIN(INITIAL);
	//printf("%s\t\tmultiline comment\n", comment);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 49 "lexer.flex"

	YY_BREAK
case 6:
YY_RULE_SETUP
#line 50 "lexer.flex"
strcat(comment, yytext);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 53 "lexer.flex"
return CLASS;
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 54 "lexer.flex"
return SUPER;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 55 "lexer.flex"
return SELF;
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 56 "lexer.flex"
return DEF;
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 57 "lexer.flex"
return RETURN;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 58 "lexer.flex"
return END;
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 60 "lexer.flex"
return IF;
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 61 "lexer.flex"
return ELSE;
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 62 "lexer.flex"
return ELSIF;
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 63 "lexer.flex"
return THEN;
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 64 "lexer.flex"
return WHILE;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 65 "lexer.flex"
return UNTIL;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 66 "lexer.flex"
return DO;
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 67 "lexer.flex"
return UNLESS;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 69 "lexer.flex"
return FALSE;
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 70 "lexer.flex"
return TRUE;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 71 "lexer.flex"
return NIL;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 73 "lexer.flex"
{ literal[0] = 0;
    BEGIN(STRING);
    }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 76 "lexer.flex"
strcat(literal,yytext);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 77 "lexer.flex"
strcat(literal,"\n");
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 78 "lexer.flex"
strcat(literal,"\\");
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 79 "lexer.flex"
strcat(literal,"\"");
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 80 "lexer.flex"
strcat(literal,"\'");
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 81 "lexer.flex"
strcat(literal,"\r");
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 82 "lexer.flex"
strcat(literal," ");
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 83 "lexer.flex"
strcat(literal,"\t");
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 84 "lexer.flex"
{
	int result;
	sscanf(yytext+1,"%o",&result);
	sprintf(literal + strlen(literal),"%c",result);
    }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 89 "lexer.flex"

	YY_BREAK
case 35:
YY_RULE_SETUP
#line 90 "lexer.flex"
{
    printf("String in\"\"\t\t%s\n", literal);
	literal[0] = 0;
    printf("+\n");
    BEGIN(EXP_IN_STRING);
	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 96 "lexer.flex"
{
    printf("%s\t\t$identifier\n", yytext);
    printf(".to_s\t\tmethod to string\n");
    printf("+\n");
	BEGIN(STRING);
	}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 102 "lexer.flex"
{
    printf("%s\t\t$identifier\n", yytext);
    printf(".to_s\t\tmethod to string\n");
    BEGIN(INITIAL);
	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 107 "lexer.flex"
{
    printf("String in\"\"\t\t%s\n", literal);
	literal[0] = 0;
    printf("+\n");
	printf("(\n");
    BEGIN(EXP_IN_STRING);
	}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 114 "lexer.flex"
{
    printf(").to_s\t\tmethod to string\n");
    printf("+\n");
    BEGIN(STRING);
    }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 119 "lexer.flex"
{
    printf(").to_s\t\tmethod to string\n");
    BEGIN(INITIAL); 
    }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 123 "lexer.flex"
{ 
    printf("String in \"\"\t\t%s\n", literal);
    BEGIN(INITIAL);
    }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 127 "lexer.flex"
{ literal[0] = 0;
    BEGIN(STRING2);
    }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 130 "lexer.flex"
strcat(literal,yytext);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 131 "lexer.flex"
strcat(literal,"\n");
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 132 "lexer.flex"
strcat(literal,"\'");
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 133 "lexer.flex"
{
    printf("String in \'\'\t\t%s\n", literal);
    BEGIN(INITIAL);
    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 138 "lexer.flex"
return ';';
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 139 "lexer.flex"
return '.';
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 140 "lexer.flex"
return ',';
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 141 "lexer.flex"
return  '{';
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 142 "lexer.flex"
return '}';
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 143 "lexer.flex"
return '[';
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 144 "lexer.flex"
return ']';
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 145 "lexer.flex"
return '(';
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 146 "lexer.flex"
return ')';
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 147 "lexer.flex"
return '+';
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 148 "lexer.flex"
return '-';
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 149 "lexer.flex"
return '*';
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 150 "lexer.flex"
return '/';
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 151 "lexer.flex"
return '=';
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 152 "lexer.flex"
return EQUAL;
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 153 "lexer.flex"
return '<';
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 154 "lexer.flex"
return '>';
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 156 "lexer.flex"
return NOTEQUAL;
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 157 "lexer.flex"
return OR;
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 158 "lexer.flex"
return AND;
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 159 "lexer.flex"
return '!';
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 161 "lexer.flex"
{
    int i, len = 0;
	long result;
	char *stop;
    for(i = 2; i < strlen(yytext); i++)
	    if(yytext[i] != '_')
            temp[len++] = yytext[i];
    temp[len] = '\0';
	result = strtol(temp, &stop, 2);
    //printf("%s => %ld\t\tbin constant\n", temp, result);
	yylval.uInt = result;
	return INT;
    }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 174 "lexer.flex"
{
    int i, len = 0;
	int result;
    for(i = 0; i < strlen(yytext); i++)
	    if(yytext[i] != '_')
            temp[len++] = yytext[i];
    temp[len] = '\0';
	_strupr(temp);
	sscanf(temp, "%X", &result);
   // printf("%s => %d\t\thex constant\n", temp, result);
    yylval.uInt = result;
	return INT;
    }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 187 "lexer.flex"
{
    int i, len = 0;
	int result;
    for(i = 0; i < strlen(yytext); i++)
	    if(yytext[i] != '_')
            temp[len++] = yytext[i];
    temp[len] = '\0';
	sscanf(temp, "%o", &result);
    //printf("%s => %d\t\toct constant\n", temp, result);
	yylval.uInt = result;
	return INT;
    }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 199 "lexer.flex"
{
    int i, len = 0;
	int result;
    for(i = 0; i < strlen(yytext); i++)
	    if(yytext[i] != '_')
            temp[len++] = yytext[i];
    temp[len] = '\0';
	sscanf(temp, "%d", &result);
    //printf("%s => %d\t\tdec constant\n", temp, result);
	yylval.uInt = result;
	return INT;
    }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 211 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return ID;
}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 216 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return ID;
}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 221 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return ID;
}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 226 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return ID;
}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 231 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return ID;
}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 236 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return ID;
}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 241 "lexer.flex"
{
	yylval.uId = (char*)malloc(sizeof(char) * strlen(yytext));
	strcpy(yylval.uId, yytext);
	return ID;
}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 246 "lexer.flex"

	YY_BREAK
case 80:
YY_RULE_SETUP
#line 247 "lexer.flex"
return EOL;
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 249 "lexer.flex"
printf("Error, unexpected lexem %s !!!!!!\n", yytext);
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 251 "lexer.flex"
ECHO;
	YY_BREAK
#line 1378 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STRING):
case YY_STATE_EOF(STRING2):
case YY_STATE_EOF(EXP_IN_STRING):
case YY_STATE_EOF(LINE_COMMENT):
case YY_STATE_EOF(MULTILINE_COMMENT):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a singled characater, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 179 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 179 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 178);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yytext_ptr = yy_c_buf_p;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						{
						yy_c_buf_p =
						yytext_ptr + YY_MORE_ADJ;
						return EOF;
						}

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;
					break;

				case EOB_ACT_LAST_MATCH:
#ifdef __cplusplus
					YY_FATAL_ERROR(
					"unexpected last match in yyinput()" );
#else
					YY_FATAL_ERROR(
					"unexpected last match in input()" );
#endif
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *str )
#else
YY_BUFFER_STATE yy_scan_string( str )
yyconst char *str;
#endif
	{
	int len;
	for ( len = 0; str[len]; ++len )
		;

	return yy_scan_bytes( str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n - YY_MORE_ADJ; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 251 "lexer.flex"


void main(int argc, char* argv[])
{
    if (argc < 2)
    {
        yyin = fopen("test1.txt", "r");
    }
    else if((yyin = fopen(argv[1], "r")) == 0)
    {
        printf("Can't read file %s\n", argv[1]);
        exit(1);
    }
	yyparse();
	test123(root);
}

